### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by confuser**
This isn't ready to merge in yet, I'll let you know once it is :)

### CODE REVIEW

**Comment by sgdc3** [comment]
Don't touch the pom file please, i know what i'm doing ;)

**Comment by confuser** [comment]
I couldn't even get it to compile in its current state from the master branch. Don't take this the wrong way, but why were you excluding Bukkit/Craftbukkit from WorldGuard/WorldEdit? It was completely unnecessary. Also this plugin doesn't use anything from Java 8, and the releases are complied with Java 7, changing it to Java 8 suddenly will affect a lot of users, most servers still use 7.

**Comment by sgdc3** [comment]
I'm not a java developer but I know Maven and how to optimize it.

**Comment by sgdc3** [comment]
I'm ok with the 1.7 thing, but keep the same build and depencies configuration

**Comment by sgdc3** [comment]
the excludes prevent maven to download 1000 different versions of bukkit. It speed up dependencies fetching and avoid weird errors with unavariable craftbukkit artifacts.

**Comment by sgdc3** [comment]
Anyway, I will adapt my enhancements to your pom and send you a PR ;)

**Comment by Hex27** [comment]
so do I merge this or not?

**Comment by confuser** [comment]
Not yet, still got a ton of work @Hex27, assuming you don't mind me refactoring a lot of this that is?

**Comment by Hex27** [comment]
I'm really new to this kind of stuff, so I'm not too sure what's going on. Would committing my old, unedited version of the plugin to master delete all the changes you guys made?

**Comment by confuser** [comment]
I'm refactoring out the commands into their own classes, as the main Kingdoms class is incredibly long and very difficult to follow anything. If you feel like I'm taking over, just say and I'll butt out, it's your plugin at the end of the day :)

**Comment by Hex27** [comment]
I don't mind. I just need help on what to do now. Not sure what I'm looking
at.

**Comment by confuser** [comment]
@Hex27 can you make sure the repo is up to date with any changes you make please, I notice there's a new release out but the repo hasn't been updated

**Comment by Hex27** [comment]
Okay

**Comment by confuser** [comment]
@Hex27 I'm going to close this, rebase and open a new PR at a later date in that case :)

**Pull request closed without merging**
